### ISSUE TITLE
resize

### ISSUE THREAD

**Issue by jasperchang504** [2020-DL-Training-Program/Lab2#3]
Hello助教
請問一下input進去neural network的size是(B, 1, C, T)
deep conv
第一步為何input data size是(C, T)
第二部為何resize成(1, C, T)呢 那Batch的部分怎麼不見了

再問一下講義上#filter是對應Conv2d的output channel嗎?

**Comment by kuanyuho** [comment]
Hello 助教您好, 

我也有相關的問題。以PPT 中的 DeepConvNet 為例
1. 請問 Conv2D 欄位 "# filters" 是代表什麼意思?
2. 請問第一層的 Conv2D size (1,5), 是代表每一筆 2x750 的資料, 會產生五張同樣大小的 feature map 嗎? 另外 mode = valid 是什麼意思呢?
3. 請問第二層的 Conv2D size = (C,1), 是如何跟第一層的 output 對應呢?
4. 請問第五層 Conv2D, Options 欄位多了 "max norm=2", 是什麼意思呢?
5. 請問最後一層的 Flatten 和 Dense 的作用為何呢?
感謝協助!

**Comment by jasperchang504** [comment]
Hi 助教
補充問一下 如果上面同學的第二點是對的,請問我的結果應該是要: (B, #filter, 1, 5) 嗎

**Comment by dddddaisy** [comment]
@jasperchang504 
架構表格上的 size 這一欄除了Input/ Reshape 是在描述輸入資料的維度資訊之外, 其他是在說明這一層要用的 kernel 大小
這邊的維度資訊主要是說明單一個 input 的大小, 所以省略了 Batch
另外 read_bci_data.py 已經把 (C, T) 到 (1, C, T) 的這一步 resize 完成了

#filter 指的是在這一層輸出的 feature map 數量, 就是由 out_channels 這個參數控制沒錯

**Comment by dddddaisy** [comment]
@kuanyuho 
1. #filter 指的是在這一層輸出的 feature map 數量
2. 架構表格上的 size 這一欄除了Input/ Reshape 是在描述輸入資料的維度資訊之外, 其他是在說明這一層要用的 kernel 大小
   mode 是在說明 padding 的方法, vaild 就是指不做任何 padding 
3. size 指的是 kernel 大小, 正確理解的話應該不會有問題
4. 啊 max_norm 通常是為了給 weight 更多限制, 不過這次的 Lab 請省略他
5. CNN架構的前半段(convolution)主要是找出特徵, 後半段(FC)則是分辨哪個特徵是屬於哪一類
    flatten 就是把二維的資料攤平成一維, Dense 就是 fully connected layer

**Comment by dddddaisy** [comment]
@jasperchang504 
對 size 的理解應該是錯了,
一組 [B, 1, 2, 750] 的資料經過 [1, 5] 的 kernel 運算後得到的 feature map 尺寸大小該如何計算可以參考以下

https://stackoverflow.com/questions/56450969/how-to-calculate-output-sizes-after-a-convolution-layer-in-a-configuration-file
![image](https://i.stack.imgur.com/3dLbS.png)
