### ISSUE TITLE
關於testing的accuracy

### ISSUE THREAD

**Issue by jasperchang504** [2020-DL-Training-Program/Lab2#4]
Hi助教 想請問一下
我照著講義上面recommend setting做,助教說就會有80% accuracy,可是我training的accuracy已經到97,98%了 但testing都在70左右
這樣是正常的嗎?

然後在問一下有什麼方向是可以大幅改善testing accuracy嗎
我兩個model就算用leakyReLU都還是70%左右test accuracy

**Comment by dddddaisy** [comment]
training acc 接近 100% 是蠻正常的
如果縮小 lr 並增加 epoch 都沒有用的話
可能要檢視一下是不是 model 架構或是 loss func 不恰當
