### ISSUE TITLE
Question about "You cannot modify the architecture of DeepConvNet" in spec

### ISSUE THREAD

**Issue by HappyStorm** [2020-DL-Training-Program/Lab2#5]
想請問關於 spec 裡面 "You cannot modify the architecture of DeepConvNet",
這是指:

- 不能調整 DeepConvNet 裡面的 "Convolution 層數" ?
- 不能調整 DeepConvNet 裡面的 "Convolution Filter 數量" ?
- 不能在 DeepConvNet 增刪 其他的 layer (e.g., BN) ?

另外 EEGNet 也適用上述的規定嗎? 還是就沒有任何限制了呢?

Thanks~

**Comment by dddddaisy** [comment]
是的 DeepConvNet 不能調整任何架構上的參數
包括 Convolution 層數, Convolution Filter 數量, 增刪其他的 layer 都不行
只能透過 batch size, lr, epoch, optimizer 來盡可能達到最高的 test acc

另外 EEGNet 唯一的限制是至少包含一組 Depthwise seperable convolution
其他的部分都開放自由調整
